In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv("cardekho_imputated.csv")

In [4]:
data.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [5]:
df = data.copy()

In [6]:
df.drop(columns=['Unnamed: 0', 'car_name', 'brand'], axis=1, inplace=True)

In [7]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [8]:
df.isnull().sum()

model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(167)

In [10]:
df[df.duplicated()]

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
197,City,8,70000,Individual,Petrol,Manual,16.80,1497,116.30,5,545000
360,Baleno,2,5000,Individual,Petrol,Automatic,21.40,1197,83.10,5,686000
1353,Swift Dzire,4,50000,Individual,Diesel,Manual,28.40,1248,74.02,5,680000
1429,Wagon R,13,100000,Individual,Petrol,Manual,18.90,1061,67.00,5,150000
1485,i20,3,50000,Individual,Petrol,Manual,18.60,1197,81.83,5,625000
...,...,...,...,...,...,...,...,...,...,...,...
15229,Swift,8,80000,Individual,Diesel,Manual,22.90,1248,74.00,5,350000
15324,Wagon R,6,50000,Individual,CNG,Manual,26.60,998,58.16,5,450000
15367,Tiago,4,30000,Individual,Petrol,Manual,23.84,1199,84.00,5,350000
15378,Grand,6,30000,Individual,Petrol,Manual,18.90,1197,82.00,5,450000
15392,Rover,5,128000,Dealer,Diesel,Automatic,12.63,2179,147.50,5,2675000

In [11]:
x = df.drop(columns='selling_price', axis=1)
y = df['selling_price']

In [12]:
x['model'].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

# Data Encoding

In [13]:
# Label Encoding for df.model bcz -> it have 120 different categories
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x['model'] = le.fit_transform(x['model'])

In [14]:
x.model

0          7
1         54
2        118
3          7
4         38
        ...
15406    117
15407     42
15408     77
15409    114
15410     25
Name: model, Length: 15411, dtype: int64

In [15]:
len(df['seller_type'].unique()), len(df['fuel_type'].unique()), len(df['transmission_type'].unique())

(3, 5, 2)

In [16]:
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [17]:
categorical_feature = df.select_dtypes(include='object').columns
numerical_feature = x.select_dtypes(exclude='object').columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

Oh = OneHotEncoder(drop='first', sparse_output=False)
stdscl = StandardScaler()

processor = ColumnTransformer([
    ("OneHotEncoder", Oh, categorical_feature),
    ("StandardScaler", stdscl, numerical_feature)
], remainder='passthrough')

In [18]:
x = processor.fit_transform(x)

In [19]:
pd.DataFrame(x)

,0,1,2,3,4,5,6,7,8,9,...,123,124,125,126,127,128,129,130,131,132
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

# Train Test split -

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [22]:
x_train

array([[ 0.        ,  0.        ,  0.        , ..., -0.76773286,
        -0.89566754, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ...,  0.92487372,
         0.9404295 , -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.55087963,
        -0.61874036, -0.40302241],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.9366097 ,
        -0.78070786, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43582879, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.04616815,
         0.06194201, -0.40302241]])

In [23]:
def metric_eval(true, pred):
    mae = mean_absolute_error(true, pred)
    mse = mean_squared_error(true, pred)
    r2 = r2_score(true, pred)
    rmse = np.sqrt(mse)
    return mae, mse, rmse, r2

In [24]:
# Multiple model comparision -
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
models = {
    "Linear" : LinearRegression(),
    "Ridge" : Ridge(),
    "Lasso" : Lasso(),
    "Decision Tree" : DecisionTreeRegressor()
}

for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(x_train, y_train)
    train_pred = model.predict(x_train)
    test_pred = model.predict(x_test)

    tr_mae, tr_mse, tr_rmse, tr_r2 =metric_eval(y_train, train_pred)
    t_mae, t_mse, t_rmse, t_r2 =metric_eval(y_test, test_pred)

    print(f"For {list(models.keys())[i]} model -----\n")
    print('Model performance for Training set')
    print("- Mean Squared Error: {:.4f}".format(tr_mse))
    print("- Root Mean Squared Error: {:.4f}".format(tr_rmse))
    print("- Mean Absolute Error: {:.4f}".format(tr_mae))
    print("- R2 Score: {:.4f}".format(tr_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Mean Squared Error: {:.4f}".format(t_mse))
    print("- Root Mean Squared Error: {:.4f}".format(t_rmse))
    print("- Mean Absolute Error: {:.4f}".format(t_mae))
    print("- R2 Score: {:.4f}".format(t_r2))
    
    print('='*35)
    print('\n')

For Linear model -----

Model performance for Training set
- Mean Squared Error: 111927776457.1274
- Root Mean Squared Error: 334556.0887
- Mean Absolute Error: 164483.3289
- R2 Score: 0.8612
----------------------------------
Model performance for Test set
- Mean Squared Error: 176691829303.5260
- Root Mean Squared Error: 420347.2723
- Mean Absolute Error: 182974.6046
- R2 Score: 0.7728
===================================


For Ridge model -----

Model performance for Training set
- Mean Squared Error: 151186776108.6367
- Root Mean Squared Error: 388827.4374
- Mean Absolute Error: 185345.3105
- R2 Score: 0.8125
----------------------------------
Model performance for Test set
- Mean Squared Error: 192977970368.4703
- Root Mean Squared Error: 439292.5795
- Mean Absolute Error: 203194.3390
- R2 Score: 0.7519
===================================


For Lasso model -----

Model performance for Training set
- Mean Squared Error: 111928433220.8099
- Root Mean Squared Error: 334557.0702
- Mean Absolute Error: 164493.4277
- R2 Score: 0.8612
----------------------------------
Model performance for Test set
- Mean Squared Error: 179513112013.0060
- Root Mean Squared Error: 423689.8772
- Mean Absolute Error: 183414.6230
- R2 Score: 0.7692
===================================


For Decision Tree model -----

Model performance for Training set
- Mean Squared Error: 426210181.9807
- Root Mean Squared Error: 20644.8585
- Mean Absolute Error: 4991.7517
- R2 Score: 0.9995
----------------------------------
Model performance for Test set
- Mean Squared Error: 104441138610.8408
- Root Mean Squared Error: 323173.5426
- Mean Absolute Error: 130586.9431
- R2 Score: 0.8657
===================================

C:\Users\anupa\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.467e+14, tolerance: 9.322e+11
  model = cd_fast.enet_coordinate_descent(

Now Selecting Decision Tree for Hyperparameter Tuning, because Decision Tree R2_score is Far better than other model

# Hyperparameter Tuning --

#### GridSearchCV

In [26]:
# Hyperparameters for GridSearchCV
from sklearn.model_selection import GridSearchCV
param_for_grid = {
    'max_depth': [5, 10, 15, 20, 25, None],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 2, 5, 10]
}

grid_cv_model = [
    ("Decision Tree", DecisionTreeRegressor(), param_for_grid)
]

In [33]:
model_best_param_Grid = {}

for name, model, param in grid_cv_model:
    GridCV = GridSearchCV(
        estimator=model,
        param_grid=param,
        cv=7,
        n_jobs=-1,
        scoring="r2",
    )
    GridCV.fit(x_train, y_train)
    model_best_param_Grid[name] = [GridCV.best_params_, GridCV.best_score_]

for val in model_best_param_Grid:
    print(model_best_param_Grid[val][0])
    print(model_best_param_Grid[val][1])

{'max_depth': 15, 'min_samples_leaf': 1, 'min_samples_split': 10}
0.8657030029230591

In [34]:
models = {
    "Decision Tree" : DecisionTreeRegressor(
        min_samples_split=10, min_samples_leaf=1, max_depth=15
    )
}


for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(x_train, y_train)

    train_pred = model.predict(x_train)
    test_pred = model.predict(x_test)

    tr_mae, tr_mse, tr_rmse, tr_r2 =metric_eval(y_train, train_pred)
    t_mae, t_mse, t_rmse, t_r2 =metric_eval(y_test, test_pred)

    print(f"For {list(models.keys())[i]} model -----\n")
    print('Model performance for Training set')
    print("- Mean Squared Error: {:.4f}".format(tr_mse))
    print("- Root Mean Squared Error: {:.4f}".format(tr_rmse))
    print("- Mean Absolute Error: {:.4f}".format(tr_mae))
    print("- R2 Score: {:.4f}".format(tr_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Mean Squared Error: {:.4f}".format(t_mse))
    print("- Root Mean Squared Error: {:.4f}".format(t_rmse))
    print("- Mean Absolute Error: {:.4f}".format(t_mae))
    print("- R2 Score: {:.4f}".format(t_r2))
    
    print('='*35)
    print('\n')

For Decision Tree model -----

Model performance for Training set
- Mean Squared Error: 16959061363.4844
- Root Mean Squared Error: 130226.9610
- Mean Absolute Error: 67424.7994
- R2 Score: 0.9790
----------------------------------
Model performance for Test set
- Mean Squared Error: 86347810740.7640
- Root Mean Squared Error: 293849.9800
- Mean Absolute Error: 120482.1016
- R2 Score: 0.8890
===================================

#### RandomSearchCV

In [40]:
from sklearn.model_selection import RandomizedSearchCV
param_for_rand = {
    "criterion" : ['squared_error', 'absolute_error', 'poisson'],
    "splitter" : ['best', 'random'],
    "max_depth" : [10, 20, 40, 60, 80, 100],
    "min_samples_split" : [2, 4, 8, 10, 20],
    "min_samples_leaf" : [1, 2, 3, 4, 5],
    "max_features": [5, 7, 8, 10],
}

random_cv_model = [
    ("Decision Tree", DecisionTreeRegressor(), param_for_rand)
]

In [42]:
model_best_param_rand ={}

for name, model, param in random_cv_model:
    RandSrchCV = RandomizedSearchCV(estimator=model,
                                    param_distributions=param,
                                    scoring="r2",
                                    cv=3,
                                    n_jobs=-1,
                                    verbose=2,
                                    n_iter=100,
                                    random_state=42
                                   )
    RandSrchCV.fit(x_train, y_train)
    model_best_param_rand[model] = [RandSrchCV.best_params_, RandSrchCV.best_score_]
    
for val in model_best_param_rand:
    print(model_best_param_rand[val][0])
    print(model_best_param_rand[val][1])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
{'splitter': 'random', 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 10, 'max_depth': 60, 'criterion': 'poisson'}
0.7353049924462068

### Final Model

In [43]:
models = {
    "Decision Tree" : DecisionTreeRegressor(
        splitter='random', min_samples_split=4, min_samples_leaf=1, max_features=10, max_depth=0, criterion='poisson'
    )
}


for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(x_train, y_train)

    train_pred = model.predict(x_train)
    test_pred = model.predict(x_test)

    tr_mae, tr_mse, tr_rmse, tr_r2 =metric_eval(y_train, train_pred)
    t_mae, t_mse, t_rmse, t_r2 =metric_eval(y_test, test_pred)

    print(f"For {list(models.keys())[i]} model -----\n")
    print('Model performance for Training set')
    print("- Mean Squared Error: {:.4f}".format(tr_mse))
    print("- Root Mean Squared Error: {:.4f}".format(tr_rmse))
    print("- Mean Absolute Error: {:.4f}".format(tr_mae))
    print("- R2 Score: {:.4f}".format(tr_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Mean Squared Error: {:.4f}".format(t_mse))
    print("- Root Mean Squared Error: {:.4f}".format(t_rmse))
    print("- Mean Absolute Error: {:.4f}".format(t_mae))
    print("- R2 Score: {:.4f}".format(t_r2))
    
    print('='*35)
    print('\n')

For Decision Tree model -----

Model performance for Training set
- Mean Squared Error: 126477293342.2737
- Root Mean Squared Error: 355636.4623
- Mean Absolute Error: 66617.2925
- R2 Score: 0.8432
----------------------------------
Model performance for Test set
- Mean Squared Error: 290459182640.8174
- Root Mean Squared Error: 538942.6525
- Mean Absolute Error: 152853.6227
- R2 Score: 0.6265
===================================

In [ ]:
### final model is -